"""init.py — `kb init <design-repo>`: one-command bring-up for a new board.

Scans a KiCad design repo, auto-discovers its root schematic / PCB / fp-lib-table /
BOM, and writes:

  1. a `kicad-bench.toml` for the project (in the kicad-bench repo's configs/ by
     default, or in-repo with --in-repo),
  2. a `.kicad-bench-config` pointer in the design repo (so every `kb` command and the
     daemons resolve the config with no env var or --config flag — see core.config),
  3. parameterized daemon units (launchd plist on macOS / systemd user unit on Linux)
     that run `kb sidecar` and `kb stage daemon` for this project, with real paths
     filled in — no hard-coded user paths.

It writes nothing into the design's `.kicad_sch` / `.kicad_pcb`; only the pointer file
and the tools/ units land in the repo. Existing files are never clobbered without
--force. After writing, it validates the config by loading it and running the same
environment check as `kb doctor`.
"""
from __future__ import annotations

import argparse
import shutil
import sys
from pathlib import Path

from .core import cli
from .core import config as cfgmod

# Directories that never contain the live project files (backups, history, output).
_EXCLUDE = ("-backups", ".history", ".git", "__pycache__")


def add_parser(sub) -> None:
    p = sub.add_parser(
        "init", help="scaffold a kicad-bench.toml + daemon units for a board repo",
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("repo", help="path to the KiCad design repo to bring up")
    p.add_argument("--name", help="project slug (default: derived from the repo dir name)")
    p.add_argument("--config-dir",
                   help="where to write <name>.toml (default: the kicad-bench repo's configs/)")
    p.add_argument("--in-repo", action="store_true",
                   help="write the config as <repo>/kicad-bench.toml instead (no pointer needed)")
    p.add_argument("--force", action="store_true", help="overwrite existing config/pointer/units")
    p.set_defaults(func=run)


# ── discovery ────────────────────────────────────────────────────────────────
def _excluded(p: Path) -> bool:
    return any(any(tok in part for tok in _EXCLUDE) for part in p.parts)


def _slug(name: str) -> str:
    out = []
    for ch in name.strip().lower():
        if ch.isalnum():
            out.append(ch)
        elif ch in " _-/":
            out.append("-")
    s = "".join(out)
    while "--" in s:
        s = s.replace("--", "-")
    return s.strip("-") or "board"


def _discover(repo: Path) -> dict:
    """Find the primary .kicad_pro and the sibling sch/pcb/fp-lib-table/BOM.
    Returns paths RELATIVE to the repo root (or None)."""
    pros = sorted((p for p in repo.rglob("*.kicad_pro") if not _excluded(p)),
                  key=lambda p: len(p.parts))
    if not pros:
        return {}
    # Prefer a .kicad_pro whose stem matches the repo name; else the shallowest.
    pro = next((p for p in pros if _slug(p.stem) == _slug(repo.name)), pros[0])
    base = pro.parent

    def rel(p: Path | None) -> str | None:
        return str(p.relative_to(repo)) if p else None

    sch = pro.with_suffix(".kicad_sch")
    if not sch.exists():
        sibs = [s for s in base.glob("*.kicad_sch") if not _excluded(s)]
        sch = sibs[0] if sibs else None
    pcb = pro.with_suffix(".kicad_pcb")
    pcb = pcb if pcb.exists() else None
    fp = base / "fp-lib-table"
    fp = fp if fp.exists() else None

    boms = [b for b in repo.rglob("*.xlsx") if not _excluded(b)]
    bom = next((b for b in boms if "bom" in b.name.lower()), boms[0] if boms else None)

    return {"pro": rel(pro), "root_sch": rel(sch), "pcb": rel(pcb),
            "fp_lib_table": rel(fp), "bom": rel(bom)}


# ── templates ────────────────────────────────────────────────────────────────
def _toml(name: str, repo: Path, d: dict, in_repo: bool) -> str:
    """Generate the kicad-bench.toml body. When the config lives outside the repo we
    set project.root; an in-repo config omits it (root defaults to the config dir)."""
    def line(key, val):
        return f'{key:<13}= "{val}"' if val else f'# {key:<11}= "TODO"'
    root_line = "" if in_repo else f'root         = "{repo}"\n'
    return f"""\
# kicad-bench config for {repo.name}. Generated by `kb init`.
# Net names and designator ranges should be sourced from the project's own
# machine-readable artifacts so this file does not duplicate (and drift from) them.

[project]
{root_line}{line("root_sch", d.get("root_sch"))}
{line("pcb", d.get("pcb"))}
{line("fp_lib_table", d.get("fp_lib_table"))}
{line("bom", d.get("bom"))}

[contracts]
# Pull the named-net list from a design-rules JSON or a markdown doc, e.g.:
#   nets = "from:scripts/design_rules_config.json"
# expected_nets = "{name}.expected_nets.json"   # node-count baseline (kb netlist-audit --emit-baseline)

# Reference-designator reservations per block; ranges expand inclusively ("R1-R9").
[contracts.designators]
# general = ["R1-R12", "C1-C32", "H1-H4"]

# Known ERC false-positives. Every entry REQUIRES a reason.
# [[erc.allow]]
# type   = "power_pin_not_driven"
# ref    = "U1"
# pin    = "7"
# reason = "…"

[fab]
# config  = "scripts/design_rules_config.json"
# stackup = "JLC04161H-3313"

# Doc tabs shown in `kb sidecar` (paths relative to the project root).
# [[sidecar.tabs]]
# title = "Build Checklist"
# file  = "docs/PCB_BUILD_CHECKLIST.html"

# Live stage-runner status (kb stage daemon writes this; gitignored).
[[sidecar.tabs]]
title = "Staged"
file  = ".stage/status.html"
"""


def _kicad_cli_dir() -> str:
    found = shutil.which("kicad-cli")
    if found:
        return str(Path(found).resolve().parent)
    return "/Applications/KiCad/KiCad.app/Contents/MacOS"


def _launchd_plist(label: str, args: list[str], repo: Path, log: str) -> str:
    pa = "\n".join(f"    <string>{a}</string>" for a in args)
    return f"""<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0"><dict>
  <key>Label</key><string>{label}</string>
  <key>ProgramArguments</key><array>
{pa}
  </array>
  <key>WorkingDirectory</key><string>{repo}</string>
  <key>EnvironmentVariables</key><dict>
    <key>PATH</key><string>{_kicad_cli_dir()}:/usr/local/bin:/usr/bin:/bin</string>
  </dict>
  <key>RunAtLoad</key><true/>
  <key>KeepAlive</key><true/>
  <key>StandardOutPath</key><string>{log}</string>
  <key>StandardErrorPath</key><string>{log}</string>
</dict></plist>
"""


def _systemd_unit(desc: str, args: list[str], repo: Path) -> str:
    return f"""[Unit]
Description={desc}
After=default.target

[Service]
Type=simple
WorkingDirectory={repo}
Environment=PATH={_kicad_cli_dir()}:/usr/local/bin:/usr/bin:/bin
ExecStart={' '.join(args)}
Restart=on-failure

[Install]
WantedBy=default.target
"""


def _write(path: Path, content: str, force: bool, made: list, skipped: list) -> None:
    if path.exists() and not force:
        skipped.append(path)
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)
    made.append(path)


# ── adopt an existing KiCad project (callable core) ──────────────────────────
def init_board(repo, *, name: str | None = None, config_dir: str | None = None,
               in_repo: bool = True, force: bool = False) -> dict:
    """Adopt an EXISTING KiCad project: write its `kicad-bench.toml` (+ a pointer when the
    config lives out-of-repo) and the sidecar/stage daemon units. NO KiCad files are
    generated — discovery only inspects what's already there. Returns
    {config_path, name, repo, discovered, made, skipped, install_hint}. Raises ValueError
    if `repo` isn't a directory or has no `.kicad_pro`. This is the programmatic entry the
    cockpit's Add-board calls; the `run()` CLI wraps it with console output + validation."""
    repo = Path(repo).expanduser().resolve()
    if not repo.is_dir():
        raise ValueError(f"not a directory: {repo}")
    name = _slug(name or repo.name)
    d = _discover(repo)
    if not d.get("pro"):
        raise ValueError(f"no .kicad_pro found under {repo} — is this a KiCad project?")

    # Where the config goes.
    if in_repo:
        cfg_path = repo / cfgmod.CONFIG_NAME
    else:
        cfg_dir = Path(config_dir).expanduser().resolve() if config_dir \
            else Path(__file__).resolve().parent.parent / "configs"
        cfg_path = cfg_dir / f"{name}.toml"

    kb = shutil.which("kb") or "kb"
    made: list[Path] = []
    skipped: list[Path] = []

    _write(cfg_path, _toml(name, repo, d, in_repo), force, made, skipped)

    # Pointer (only needed when the config lives outside the repo).
    if not in_repo:
        _write(repo / cfgmod.POINTER_NAME,
               f"# kicad-bench config location for this repo (see `kb init`).\n{cfg_path}\n",
               force, made, skipped)

    # Daemon units — sidecar (live dashboard) + stage (lock-aware queue).
    cfgs = str(cfg_path)
    if sys.platform == "darwin":
        units = repo / "tools" / "launchd"
        _write(units / f"com.kicadbench.{name}.sidecar.plist",
               _launchd_plist(f"com.kicadbench.{name}.sidecar",
                              [kb, "sidecar", "--config", cfgs, "--host", "0.0.0.0",
                               "--port", "8765"], repo, f"/tmp/kicadbench-{name}-sidecar.log"),
               force, made, skipped)
        _write(units / f"com.kicadbench.{name}.stage.plist",
               _launchd_plist(f"com.kicadbench.{name}.stage",
                              [kb, "stage", "daemon", "--config", cfgs], repo,
                              f"/tmp/kicadbench-{name}-stage.log"),
               force, made, skipped)
        install_hint = (f"  launchctl load -w {units}/com.kicadbench.{name}.sidecar.plist\n"
                        f"  launchctl load -w {units}/com.kicadbench.{name}.stage.plist")
    else:
        units = repo / "tools" / "systemd"
        _write(units / f"kicadbench-{name}-sidecar.service",
               _systemd_unit(f"kicad-bench sidecar ({name})",
                             [kb, "sidecar", "--config", cfgs, "--host", "0.0.0.0",
                              "--port", "8765"], repo),
               force, made, skipped)
        _write(units / f"kicadbench-{name}-stage.service",
               _systemd_unit(f"kicad-bench stage daemon ({name})",
                             [kb, "stage", "daemon", "--config", cfgs], repo),
               force, made, skipped)
        install_hint = (f"  systemctl --user enable --now "
                        f"{units.name}/kicadbench-{name}-sidecar.service  # (after `cp` to ~/.config/systemd/user/)")

    return {"config_path": cfg_path, "name": name, "repo": repo, "discovered": d,
            "made": made, "skipped": skipped, "install_hint": install_hint}


# ── run (CLI wrapper: console output + validation) ───────────────────────────
def run(args) -> int:
    try:
        r = init_board(args.repo, name=args.name, config_dir=args.config_dir,
                       in_repo=args.in_repo, force=args.force)
    except ValueError as e:
        print(f"error: {e}", file=sys.stderr)
        return 2

    name, repo, d, cfg_path = r["name"], r["repo"], r["discovered"], r["config_path"]
    print(f"== kb init: {name} ==")
    print(f"  repo:          {repo}")
    for k in ("pro", "root_sch", "pcb", "fp_lib_table", "bom"):
        print(f"  {k:<13} {d.get(k) or '— (not found)'}")
    for p in r["made"]:
        print(f"  + wrote {p}")
    for p in r["skipped"]:
        print(f"  · exists, kept (use --force): {p}")

    # Validate.
    print("== validate ==")
    if cli.have_kicad_cli():
        print(f"  ✓ kicad-cli: {cli.version()}")
    else:
        print("  ✗ kicad-cli not on PATH (install KiCad 10)")
    try:
        cfg = cfgmod.load(cfg_path)
        print(f"  ✓ config loads: {cfg_path}")
        if cfg.root_sch and cfg.root_sch.exists():
            print(f"  ✓ root schematic resolves: {cfg.root_sch}")
        elif cfg.root_sch:
            print(f"  ! root schematic not found at {cfg.root_sch}")
    except Exception as e:  # noqa: BLE001
        print(f"  ✗ config failed to load: {e}")
        return 2

    print("== next ==")
    print(f"  kb audit            # from inside {repo} (config auto-resolves via the pointer)")
    print(f"  kb sidecar          # live dashboard on http://127.0.0.1:8765")
    print("  # fill in [contracts]/[fab] in the toml, then install the daemon units:")
    print(r["install_hint"])
    return 0
